name: url_launcher_example
description: Demonstrates the Windows implementation of the url_launcher plugin.
publish_to: none

environment:
<<<<<<< HEAD
<<<<<<< HEAD
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"
=======
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
>>>>>>> refs/remotes/origin/main
=======
  sdk: ^3.1.0
  flutter: ">=3.13.0"
>>>>>>> refs/remotes/origin/main

dependencies:
  flutter:
    sdk: flutter
  url_launcher_platform_interface: 
    git: https://github.com/kumsumit/url_launcher_platform_interface.git
  url_launcher_windows:
    # When depending on this package from a real application you should use:
    #   url_launcher_windows: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
