name: url_launcher_windows
publish_to: none
description: Windows implementation of the url_launcher plugin.
repository: https://github.com/flutter/packages/tree/main/packages/url_launcher/url_launcher_windows
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+url_launcher%22
version: 3.1.2

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.3"

flutter:
  plugin:
    implements: url_launcher
    platforms:
      windows:
        pluginClass: UrlLauncherWindows
        dartPluginClass: UrlLauncherWindows

dependencies:
  flutter:
    sdk: flutter
  url_launcher_platform_interface: 
    git: https://github.com/kumsumit/url_launcher_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: 
    git: https://github.com/kumsumit/pigeon.git
  test: ^1.16.3

topics:
  - links
  - os-integration
  - url-launcher
  - urls
